- dockerImage: instill-ai/source-http
  spec:
    documentationUrl: https://www.instill.tech/docs/source-connectors/http
    connectionSpecification:
      $schema: http://json-schema.org/draft-07/schema#
      additionalProperties: false
      properties: {}
      required: []
      title: HTTP Source Connector Spec
      type: object
    supportsIncremental: false
    supportsNormalization: false
    supportsDBT: false
    supported_destination_sync_modes: []
- dockerImage: instill-ai/source-grpc
  spec:
    documentationUrl: https://www.instill.tech/docs/source-connectors/grpc
    connectionSpecification:
      $schema: http://json-schema.org/draft-07/schema#
      additionalProperties: false
      properties: {}
      required: []
      title: gRPC Source Connector Spec
      type: object
    supportsIncremental: false
    supportsNormalization: false
    supportsDBT: false
    supported_destination_sync_modes: []
